services:
  play.catalog.service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      # - ASPNETCORE_HTTPS_PORTS=8081
    ports:
      - 5000:8080
    #   - 5001:8081
    # volumes:
    #   - ./UserSecrets:/home/app/.microsoft/usersecrets:ro
    #   - ./Https:/home/app/.aspnet/https:ro
  play.inventory.service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      #- ASPNETCORE_HTTPS_PORTS=8081
    ports:
      - 5002:8080
      #- 5003:8081
    # volumes:
    #   - ./UserSecrets:/home/app/.microsoft/usersecrets:ro
    #   - ./Https:/home/app/.aspnet/https:ro


